language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"
before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install: NV=$(node --version); if [ ${NV:0:5} = "v0.12" ]; then npm install; else yarn; fi
script:
  - npm run build
  - npm run lint
  - npm run pretest && npm run test:unit
  - npm run codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - 'uwdub:Ry6mwlUX1aZevqiqmYLiA3N1'
    on_success: never
    on_failure: change
cache:
  directories:
  - $HOME/.yarn-cache
